#!/usr/bin/env bash
# Read the /etc/passwd file line by line
while IFS=: read -r username password uid gid description home_directory shell
do
    echo "The user $username is part of the $gid gang, lives in $home_directory and rides $shell. **USER ID's** place is protected by the passcode $password, more info about the user here: $description"
done < /etc/passwd

