#!/usr/bin/env bash
# This script displays hours and minutes

hour=0
minute=1

# Loop through hours from 0 to 12
while [ $hour -le 12 ]; do
    # Loop through minutes from 1 to 59
    while [ $minute -lt 60 ]; do
        echo "$hour:$minute"
        minute=$((minute + 1)) # Increment minute
    done
    hour=$((hour + 1)) # Increment hour
done 
