#!/usr/bin/env bash
# This script displays hours and minutes

hour=0
while [ $hour -le 12 ]; do
    echo "Hour: $hour" # Display the current hour

    # Initialize minute variable
    minute=1

    # Loop through minutes from 1 to 59
    while [ $minute -lt 60 ]; do
        echo "$minute" # Display the current minute
        minute=$((minute + 1)) # Increment minute
    done

    hour=$((hour + 1)) # Increment hour
done
